config/routes.rb
MicroApp::Application.routes.draw do
  get "users/new"

  get "users/edit"

  get "home/index"

  get "user_sessions/new"

  resources :users do 
    resources :microposts
  end
 root :to => 'users#new'
 resources :user_sessions
 match 'login' => "user_sessions#new",      :as => :login
 match 'logout' => "user_sessions#destroy", :as => :logout
 #root :to => 'home#index'

end 

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    can :manage Micropost do |m|
        m.user == user
    end
  end
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
  validates :content, :length => { maximum: 140}
end
 

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :emails, :password, :password_confirmation
	acts_as_authentic do |c|
    c.login_field = 'emails'
  end
  has_many :microposts
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
  def to_key

        new_record? ? nil : [ self.send(self.class.primary_key) ]

      end


      def persisted?

        false

      end

    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

      protect_from_forgery

      helper_method :current_user_session, :current_user

      before_filter :new_user_session

      private

      def current_user_session

        return @current_user_session if defined?(@current_user_session)

        @current_user_session = UserSession.find

      end

       

      def current_user

        return @current_user if defined?(@current_user)

        @current_user = current_user_session && current_user_session.record

      end


      def new_user_session

        @new_user_session = UserSession.new

      end

    end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :get_user
  before_filter :get_micropost, except: [:show, :edit, :update, :destroy]
  # GET /microposts
  # GET /microposts.json
  def index
    # @microposts = Micropost.all
    #@user = User.find(params[:user_id])
    @microposts = @user.microposts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])
    #@user = User.find(params[:user_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new(:user_id => "user_id")
    #@user = User.find(params[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
    #@user = User.find(params[:user_id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])
    #@user = User.find(params[:user_id])
    Rails.logger.info "arstarstarst  #{params[:user_id]}"

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to [@user, @micropost], notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])
    #@user = User.find(params[:user_id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to [@user, @micropost], notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
  def get_user
     @user = User.find(params[:user_id])
  end 
  def get_micropost
    @micropost = Micropost.find(params[:id])
  end 
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new

        @user_session = UserSession.new

      end

      

      def create

        @user_session = UserSession.new(params[:user_session])

        if @user_session.save

          flash[:notice] = "Login successful!"

          redirect_to '/posts'

        else

          flash[:notice] = "Login error!"

          render :action => :new

        end

      end


      def destroy

        @user_session = UserSession.find

        @user_session.destroy

        flash[:notice] = "Successfully logged out."

        redirect_to "/posts"

      end


    end

  

app/controllers/users_controller.rb
 class UsersController < ApplicationController
  def new

      @user = User.new

    end

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end



    def edit

      @user = current_user

    end


    def create

      @user = User.new(params[:user])

      if @user.save

        flash[:notice] = "Create successful!"

        redirect_to "#"

      else

        render :action => 'new'

      end

    end


    def update

      @user = current_user


      if @user.update_attributes params[:user]

        flash[:notice] = "Update successful!"

        redirect_to "/my_account"

      else

        render :action => :edit

      end

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MicroApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Micro Twitter</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Users", users_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
    <div class="span3">
      <h2>About Us</h2>
      <p>Write some static text here...</p>
    </div>
  </div>
</div>

</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for([@user,@micropost])  do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', user_micropost_path(@user, @micropost) %> |
<%= link_to 'Back'%>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %> </td>
     <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', user_micropost_path(@user,micropost) %></td>
     <% if can? :update, @article %>  
    <td><%= link_to 'Edit', edit_user_micropost_path(@user,micropost) %></td>
    <% if can? :destroy, @article %> 
    <td><%= link_to 'Destroy', user_micropost_path(@user,micropost), method: :delete, data: { confirm: 'Are you sure?' } %></td>  
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_user_micropost_path(@user) %>

app/views/microposts/new.html.erb
<h1>New <%=@user.name %>'s micropost</h1>

<%= render 'form' %>

<%= link_to 'Back' %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @user.name%>
</p>

<p>
  <b>Created_at:</b>
  <%= @user.created_at%>
</p>


<%= link_to 'Edit', edit_user_micropost_path(@user,@micropost) %> |
<%= link_to 'Back' %>
<%= link_to 'Destroy', edit_user_micropost_path(@user,@micropost) %> |

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
<h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
<ul>
<% target.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/user_sessions/new.html.erb
 <h1>Login</h1>
# app/views/user_sessions/new.html.erb
<%= form_for [@user_session], :as => :user_session, :url => { :action => "create" } do |f| %>
   <%= render "shared/error_messages", :target => @user_session %>
  <%= f.label :email %><br />
  <%= f.text_field :emails %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

      <% if @user.errors.any? %>

        <div id="error_explanation">

          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>


          <ul>

          <% @user.errors.full_messages.each do |msg| %>

            <li><%= msg %></li>

          <% end %>

          </ul>

        </div>

      <% end %>


      <div class="field">

        <%= f.label :username %><br />

        <%= f.text_field :name %>

      </div>

      <div class="field">

        <%= f.label :email %><br />

        <%= f.text_field :emails %>

      </div>

      <div class="field">

        <%= f.label :password %><br />

        <%= f.text_field :password %>

      </div>

      <div class="field">

        <%= f.label :password_confirmation %><br />

        <%= f.text_field :password_confirmation %>

      </div>

      <div class="actions">

        <%= f.submit %>

      </div>

    <% end %>

  

app/views/users/edit.html.erb
<h1>Editing user</h1>


      <%= render 'form' %>


      <%= link_to 'Show', @user %> |

      <%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:emails) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.emails %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New user</h1>


    <%= render 'form' %>


    <%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emails) %>:</strong></dt>
  <dd><%= @user.emails %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>